version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./frontend:/app/frontend  # ✅
    environment:
      - PYTHONUNBUFFERED=1